Make lbevreactor remove connection from new connections list on discard
WHen connection is destroyed it is not removed from `self._new_conns`,
which is why the following error happens:
```
  File "/123/cassandra/io/libevreactor.py", line 197, in _loop_will_run
    conn._read_watcher.start()
AttributeError: 'NoneType' object has no attribute 'start'
```