Handle case where there is both TTL and TIMESTAMP
The existing code causes an error like so:
```
cassandra.protocol.SyntaxException: <Error from server: code=2000 [Syntax error in CQL query] message="line 1:101 missing EOF at 'TIMESTAMP' (...({row}) USING TTL {ttl} [USING] TIMESTAMP {timestamp})">
```

by checking for the ttl in the timestamp code we can change the generated query from `USING TTL {ttl} USING TIMESTAMP {timestamp}` => `USING TTL {ttl} AND TIMESTAMP {timestamp}`, which is correct.