cicd: fix windows builds
VSCode cl.exe fails to recognize some of the syntax:
```
    cassandra\c_shard_info.c(3083): error C2065: '__uint128_t': undeclared identifier
    cassandra\c_shard_info.c(3083): error C2146: syntax error: missing ')' before identifier '__pyx_v_biased_token'
    cassandra\c_shard_info.c(3083): error C2059: syntax error: ')'
    cassandra\c_shard_info.c(3083): error C2059: syntax error: ')'
    cassandra\c_shard_info.c(3083): error C2059: syntax error: ')'
```
Let's switch to clang.