deafult to disable_shardaware_port=False when using scylla_cloud
Since we are going to work via a loadbalancer, shardaware base on port
can't work for us.

also if some would try to enable it via configuration, we'll fail
like this:

```
Traceback (most recent call last):
  File "../python-driver/cloud_config.py", line 59, in <module>
    thread1()
  File "../python-driver/cloud_config.py", line 39, in thread1
    cluster = Cluster(scylla_cloud='../config_data.yaml', connect_timeout=60, control_connection_timeout=30,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../python-driver/cassandra/cluster.py", line 1167, in __init__
    raise ValueError("shard_aware_options.disable_shardaware_port=False "
ValueError: shard_aware_options.disable_shardaware_port=False cannot be specified with a scylla cloud configuration
```

Fixes: scylladb/scylla-operator#1104